[server]
headless = true
address = "127.0.0.1"
port = 8501

[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#f5f7fa"
secondaryBackgroundColor = "#e9ecef"
textColor = "#262730"
font = "sans-serif"

[browser]
gatherUsageStats = false

[logger]
level = "info"
